name: paytym
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.3.6"

dependencies:
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.1
  flutter_native_splash: ^2.2.11
  flutter_secure_storage: ^6.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.5
  fluttertoast: ^8.1.1
  get: ^4.6.5
  intl: ^0.17.0
  lottie: ^1.4.3
  pie_chart: ^5.3.2
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/svg/
    - assets/pdf/
    - assets/png/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
